name: Deploy on Vercel Production
run-name: ${{ github.actor }} is deploying to Production 🚀

on:
  workflow_dispatch:

jobs:
  deploy_prod:
    if: github.ref == 'refs/heads/work'
    name: Deploy Production
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Pull Vercel Environment
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build and Deploy to Vercel
        run: |
          url=$(npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} -e VITE_CRYPTOCOMPARE_APIKEY=${{ secrets.VITE_CRYPTOCOMPARE_APIKEY }})
          echo "url=$url" >> $GITHUB_OUTPUT
          echo "Production deployed at: $url"
