name: Deploy Production to Vercel

on:
  push:
    branches:
      - main   # 👈 adjust if your production branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js (adjust version to match your project)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build project for PRODUCTION
      - name: Build project
        run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy prebuilt output to PRODUCTION
      - name: Deploy to Vercel (Production)
        id: deploy
        run: |
          url=$(npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$url" >> $GITHUB_OUTPUT
          echo "✅ Production deployed: $url"
